require "azure.launch"
require "azure.options"
require "azure.keymaps"
require "azure.autocmds"
require "azure.python"

spec "azure.colorschemes.darkplus"

spec "azure.colorscheme"
spec "azure.devicons"
spec "azure.treesitter"
spec "azure.mason"
spec "azure.schemastore"
spec "azure.lspconfig"
spec "azure.cmp"
spec "azure.none-ls"
spec "azure.maximizer"
spec "azure.telescope"
spec "azure.whichkey"
spec "azure.project"
spec "azure.nvimtree"
spec "azure.lualine"
spec "azure.comment"
spec "azure.vim-surround"
spec "azure.navic"
spec "azure.breadcrumbs"
spec "azure.harpoon"
spec "azure.illuminate"
spec "azure.gitsigns"
spec "azure.autopairs"
spec "azure.neogit"
spec "azure.alpha"
-- spec "azure.indentline"
spec "azure.toggleterm"
spec "azure.nvim-dap"

spec "azure.extras.copilot"
spec "azure.extras.tabby"
-- spec "azure.extras.neoscroll"
-- spec "azure.extras.oil"
spec "azure.extras.ufo"
-- spec "azure.extras.lab"
-- spec "azure.extras.cellular-automaton"
spec "azure.extras.eyeliner"
-- spec "azure.extras.neotab"
spec "azure.extras.gitlinker"
spec "azure.extras.fidget"
spec "azure.extras.bqf"
spec "azure.extras.navbuddy"
spec "azure.extras.trouble"
spec "azure.extras.zen"
-- spec "azure.extras.conjure"
spec "azure.extras.mason-nvim-dap"
spec "azure.extras.nvim-dap-ui"

require "azure.lazy"
